package world.podo.emergency.infrastructure.public_api;

import lombok.experimental.UtilityClass;

import java.util.HashMap;
import java.util.Map;

@UtilityClass
public class PublicApiCountryIsoCodeUtils {
    private static final Map<String, String> DEFAULT_COUNTRY_ISO_CODE_MAP;

    static {
        DEFAULT_COUNTRY_ISO_CODE_MAP = new HashMap<>();
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("가나", "GHA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("가봉", "GAB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("가이아나", "GUY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("감비아", "GMB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("건지 섬", "GGY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("과들루프", "GLP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("과테말라", "GTM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("괌", "GUM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("그레나다", "GRD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("그리스", "GRC");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("그린란드", "GRL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("기니", "GIN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("기니비사우", "GNB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("나미비아", "NAM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("나우루", "NRU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("나이지리아", "NGA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("남극", "ATA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("남수단", "SSD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("남아프리카 공화국", "ZAF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("네덜란드", "NLD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("네덜란드령 안틸레스", "ANT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("네팔", "NPL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("노르웨이", "NOR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("노퍽 섬", "NFK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("누벨칼레도니", "NCL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("뉴질랜드", "NZL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("니우에", "NIU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("니제르", "NER");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("니카라과", "NIC");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("대한민국", "KOR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("덴마크", "DNK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("도미니카 공화국", "DOM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("도미니카 연방", "DMA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("독일", "DEU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("동티모르", "TLS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("라오스", "LAO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("라이베리아", "LBR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("라트비아", "LVA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("러시아", "RUS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("레바논", "LBN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("레소토", "LSO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("레위니옹", "REU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("루마니아", "ROU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("룩셈부르크", "LUX");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("르완다", "RWA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("리비아", "LBY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("리투아니아", "LTU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("리히텐슈타인", "LIE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마다가스카르", "MDG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마르티니크", "MTQ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마셜 제도", "MHL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마요트", "MYT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마카오", "MAC");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("마케도니아 공화국", "MKD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("말라위", "MWI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("말레이시아", "MYS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("말리", "MLI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("맨 섬", "IMN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("멕시코", "MEX");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("모나코", "MCO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("모로코", "MAR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("모리셔스", "MUS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("모리타니", "MRT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("모잠비크", "MOZ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몬테네그로", "MNE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몬트세랫", "MSR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몰도바", "MDA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몰디브", "MDV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몰타", "MLT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("몽골", "MNG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("미국", "USA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("미국령 군소 제도", "UMI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("미국령 버진아일랜드", "VIR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("미얀마", "MMR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("미크로네시아 연방", "FSM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("바누아투", "VUT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("바레인", "BHR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("바베이도스", "BRB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("바티칸 시국", "VAT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("바하마", "BHS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("방글라데시", "BGD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("버뮤다", "BMU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("베냉", "BEN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("베네수엘라", "VEN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("베트남", "VNM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("벨기에", "BEL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("벨라루스", "BLR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("벨리즈", "BLZ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("보스니아 헤르체고비나", "BIH");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("보츠와나", "BWA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("볼리비아", "BOL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("부룬디", "BDI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("부르키나파소", "BFA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("부베 섬", "BVT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("부탄", "BTN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("북마리아나 제도", "MNP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("불가리아", "BGR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("브라질", "BRA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("브루나이", "BRN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("사모아", "WSM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("사우디아라비아", "SAU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("사우스조지아 사우스샌드위치 제도", "SGS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("산마리노", "SMR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("상투메 프린시페", "STP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("생피에르 미클롱", "SPM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("서사하라", "ESH");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세네갈", "SEN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세르비아", "SRB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세이셸", "SYC");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세인트루시아", "LCA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세인트빈센트 그레나딘", "VCT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세인트키츠 네비스", "KNA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("세인트헬레나", "SHN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("소말리아", "SOM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("솔로몬 제도", "SLB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("수단", "SDN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("수리남", "SUR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스리랑카", "LKA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스발바르 얀마옌", "SJM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스와질란드", "SWZ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스웨덴", "SWE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스위스", "CHE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("스페인", "ESP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("슬로바키아", "SVK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("슬로베니아", "SVN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("시리아", "SYR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("시에라리온", "SLE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("싱가포르", "SGP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아랍에미리트", "ARE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아루바", "ABW");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아르메니아", "ARM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아르헨티나", "ARG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아메리칸사모아", "ASM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아이슬란드", "ISL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아이티", "HTI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아일랜드", "IRL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아제르바이잔", "AZE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("아프가니스탄", "AFG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("안도라", "AND");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("알바니아", "ALB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("알제리", "DZA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("앙골라", "AGO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("앤티가 바부다", "ATG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("앵귈라", "AIA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("에리트레아", "ERI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("에스토니아", "EST");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("에콰도르", "ECU");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("에티오피아", "ETH");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("엘살바도르", "SLV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("영국", "GBR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("영국령 버진아일랜드", "VGB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("영국령 인도양 지역", "IOT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("예멘", "YEM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("오만", "OMN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("오스트레일리아", "AUS");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("오스트리아", "AUT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("온두라스", "HND");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("올란드 제도", "ALA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("왈리스 퓌튀나", "WLF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("요르단", "JOR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("우간다", "UGA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("우루과이", "URY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("우즈베키스탄", "UZB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("우크라이나", "UKR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("이라크", "IRQ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("이란", "IRN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("이스라엘", "ISR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("이집트", "EGY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("이탈리아", "ITA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("인도", "IND");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("인도네시아", "IDN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("일본", "JPN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("자메이카", "JAM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("잠비아", "ZMB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("저지 섬", "JEY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("적도 기니", "GNQ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("조선민주주의인민공화국", "PRK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("조지아", "GEO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("중앙아프리카 공화국", "CAF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("중화민국", "TWN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("중화인민공화국", "CHN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("지부티", "DJI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("지브롤터", "GIB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("짐바브웨", "ZWE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("차드", "TCD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("체코", "CZE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("칠레", "CHL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("카메룬", "CMR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("카보베르데", "CPV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("카자흐스탄", "KAZ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("카타르", "QAT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("캄보디아", "KHM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("캐나다", "CAN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("케냐", "KEN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("케이맨 제도", "CYM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("코모로", "COM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("코스타리카", "CRI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("코코스 제도", "CCK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("코트디부아르", "CIV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("콜롬비아", "COL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("콩고 공화국", "COG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("콩고 민주 공화국", "COD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("쿠바", "CUB");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("쿠웨이트", "KWT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("쿡 제도", "COK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("크로아티아", "HRV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("크리스마스 섬", "CXR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("키르기스스탄", "KGZ");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("키리바시", "KIR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("키프로스", "CYP");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("타이", "THA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("타지키스탄", "TJK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("탄자니아", "TZA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("터크스 케이커스 제도", "TCA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("터키", "TUR");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("토고", "TGO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("토켈라우", "TKL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("통가", "TON");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("투르크메니스탄", "TKM");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("투발루", "TUV");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("튀니지", "TUN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("트리니다드 토바고", "TTO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("파나마", "PAN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("파라과이", "PRY");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("파키스탄", "PAK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("파푸아 뉴기니", "PNG");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("팔라우", "PLW");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("팔레스타인", "PSE");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("페로 제도", "FRO");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("페루", "PER");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("포르투갈", "PRT");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("포클랜드 제도", "FLK");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("폴란드", "POL");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("푸에르토리코", "PRI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("프랑스", "FRA");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("프랑스령 기아나", "GUF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("프랑스령 남부와 남극 지역", "ATF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("프랑스령 폴리네시아", "PYF");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("피지", "FJI");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("핀란드", "FIN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("핏케언 제도", "PCN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("허드 맥도널드 제도", "HMD");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("헝가리", "HUN");
        DEFAULT_COUNTRY_ISO_CODE_MAP.put("홍콩", "HKG");
    }

    public String getIsoCode(String name) {
        return DEFAULT_COUNTRY_ISO_CODE_MAP.get(name);
    }
}
