package world.podo.travelable.infrastructure.public_api;

import jdk.nashorn.internal.ir.annotations.Ignore;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import world.podo.travelable.domain.country.WarningFetchValue;

import java.util.List;

@ActiveProfiles("local")
@SpringBootTest
class PublicApiWarningFetchServiceTest {
    @Autowired
    private PublicApiWarningFetchService sut;

    @Ignore
    @Test
    public void test() {
        List<WarningFetchValue> values = sut.fetch();
        values.forEach(System.out::println);
    }

    /**
     * {continent=중동/아프리카, countryEnName=Libya, countryName=리비아, id=375, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=FILE_000000000002230&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=FILE_000000000002230&file_sn=3, isoCode=LBY, wrtDt=2011-12-07}
     * {continent=미주, countryEnName=Colombia, countryName=콜롬비아, id=213, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_213&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_213&file_sn=3, isoCode=COL, limitaNote=베네수엘라 국경지역 20km, 뚜마코 시, 바예델카우카주(깔리 시 제외), 아라우카주, 카우카주, 안티오키아주 일부, 초코주 일부, 카케타주 일부  , limitaPartial=철수권고(일부), wrtDt=2011-09-19}
     * {continent=중동/아프리카, countryEnName=Syria, countryName=시리아, id=131, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_131&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_131&file_sn=3, isoCode=SYR, wrtDt=2011-08-30}
     * {continent=중동/아프리카, countryEnName=Nigeria, countryName=나이지리아, id=18, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_18&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_18&file_sn=3, isoCode=NGA, limitaNote=니제르델타 부근 8개 주(Delta, Bayelsa, Rivers, Akwa Ibom, Imo, Abia, Edo, Anambra) 및 Plateau, Borno, Yobe, Kano, Kaduna, Bauchi, Adamawa, Abuja, Nasarawa, Zamfara, Sokoto, Katsina, Jigawa, Combe, Taraba주, limitaPartial=철수권고(일부), wrtDt=2011-08-09}
     * {continent=중동/아프리카, countryEnName=Somalia, countryName=소말리아, id=120, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_120&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_120&file_sn=3, isoCode=SOM, wrtDt=2011-08-08}
     * {continent=중동/아프리카, countryEnName=Iraq, countryName=이라크, id=174, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_174&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_174&file_sn=3, isoCode=IRQ, wrtDt=2011-08-08}
     * {continent=아시아/태평양, countryEnName=Afghanistan, countryName=아프가니스탄, id=284, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_284&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_284&file_sn=3, isoCode=AFG, wrtDt=2011-08-08}
     * {continent=중동/아프리카, countryEnName=Yemen, countryName=예멘, id=294, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_294&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_294&file_sn=3, isoCode=YEM, wrtDt=2011-08-08}
     * {continent=유럽, countryEnName=Azerbaijan, countryName=아제르바이잔, id=335, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_335&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_335&file_sn=3, isoCode=AZE, limitaNote=나고르노-카라바흐 및 인근 7개 지역(아그담(Aghdam), 피줄리(Fizuli), 자브라일(Jabrayil), 장길란(Zanglian), 구바들리(Guabadly), 라친(Lachin), 켈바자르(Kelbajar)), limitaPartial=철수권고(일부), wrtDt=2011-08-08}
     * {continent=중동/아프리카, countryEnName=Sudan, countryName=수단, id=122, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_122&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_122&file_sn=3, isoCode=SDN, limitaNote=다르푸르지역 3개 주, 남코르도판 주, 블루나일 주, 화이트나일 주(코스티시 이남지역), limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=아시아/태평양, countryEnName=Tajikistan, countryName=타지키스탄, id=302, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_302&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_302&file_sn=3, isoCode=TJK, limitaNote=아프가니스탄 국경 지역, limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=중동/아프리카, countryEnName=Eritrea, countryName=에리트레아, id=338, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_338&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_338&file_sn=3, isoCode=ERI, limitaNote=에디오피아ㆍ수단ㆍ지부티 국경지역, limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=유럽, countryEnName=Kosovo, countryName=코소보, id=367, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_367&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_367&file_sn=3, isoCode=RKS, limitaNote=미트로비차 북부(Zubin Potok, Zveçan, Leposaviq), limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=중동/아프리카, countryEnName=Republic of South Sudan, countryName=남수단, id=373, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_373&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_373&file_sn=3, isoCode=SSD, limita=철수권고, limitaNote=전지역 전 지역, wrtDt=2011-08-05}
     * {continent=아시아/태평양, countryEnName=Myanmar, countryName=미얀마, id=75, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_75&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_75&file_sn=3, isoCode=MMR, limitaNote=인도ㆍ중국ㆍ라오스ㆍ태국 국경지역, 라카인 주(마웅도, 부띠다웅, 짜욱도, 민뱌, 므라욱우, 폰나쭌, 예디다웅), 친 주(빨레와, 마투피), limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=아시아/태평양, countryEnName=Bangladesh, countryName=방글라데시, id=82, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_82&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_82&file_sn=3, isoCode=BGD, limitaNote=동남부 치타공 힐 트랙스 지역, limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=중동/아프리카, countryEnName=Burkina Faso, countryName=부르키나파소, id=94, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_94&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_94&file_sn=3, isoCode=BFA, limitaNote=북부(Nord), 사헬(Sahel), 중북부(Centre-Nod), 중동부(Centre-Est), 동부 주(Est), 말리 접경 40km 이내 지역, limitaPartial=철수권고(일부), wrtDt=2011-08-05}
     * {continent=아시아/태평양, countryEnName=Thailand, countryName=태국, id=260, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_260&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_260&file_sn=3, isoCode=THA, limitaNote=나라티왓 주, 파타니 주, 얄라 주, 송클라 주 남부 말레이시아 국경지역, limitaPartial=철수권고(일부), wrtDt=2011-08-04}
     * {continent=유럽, countryEnName=Georgia, countryName=조지아, id=332, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_332&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_332&file_sn=3, isoCode=GEO, limitaNote=남 오세티아, 압하지아, limitaPartial=철수권고(일부), wrtDt=2011-08-04}
     * {continent=아시아/태평양, countryEnName=Philippines, countryName=필리핀, id=252, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_252&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_252&file_sn=3, isoCode=PHL, limitaNote=팔라완섬 아볼란 및 나라 이남 지역, 민다나오섬(잠보앙가, 다바오/카가얀데오로시 제외), limitaPartial=철수권고(일부), wrtDt=2011-07-01}
     * {continent=중동/아프리카, countryEnName=Cote d Ivoire, countryName=코트디부아르, id=212, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_212&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_212&file_sn=3, isoCode=CIV, limitaNote=라이베리아ㆍ기니와 국경을 접한 서부 지역(Denguele주, Montagnes주, Bafing주), limitaPartial=철수권고(일부), wrtDt=2011-06-30}
     * {continent=아시아/태평양, countryEnName=Japan, countryName=일본, id=183, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_183&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_183&file_sn=3, isoCode=JPN, limitaNote=후쿠시마 원전 반경 30km 이내 및 일본 정부 지정 피난지시구역, limitaPartial=철수권고(일부), wrtDt=2011-06-20}
     * {continent=유럽, countryEnName=Russia, countryName=러시아, id=39, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_39&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_39&file_sn=3, isoCode=RUS, limitaNote=북카프카즈 지역 : 체첸, 다게스탄, 세베로오세티야(북오세티아), 카바르디노발카르(카바르티노-발카리야 공화국), 잉귀쉬(잉구세티아), 카라차예보체르케스카야(까라차이-체르케스), 아디게이(아디게야), limitaPartial=철수권고(일부), wrtDt=2011-05-31}
     * {continent=중동/아프리카, countryEnName=Algeria, countryName=알제리, id=150, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_150&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_150&file_sn=3, isoCode=DZA, limitaNote=카빌리 지역 6개주 산악지역(부메르데스, 부아라, 티지 우주, 베자이아, 보르즈부아레리즈, 지젤), 국경지역(튀니지(테베사, 엘웨드 동부, 오아글라 동부), 리비아(일리지 동부), 니제르ㆍ말리ㆍ모리타니(타만라셋 남부, 아드라르 남서부, 틴두프 남서부)), limitaPartial=철수권고(일부), wrtDt=2011-04-04}
     * {continent=아시아/태평양, countryEnName=India, countryName=인도, id=285, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_285&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_285&file_sn=3, isoCode=IND, limitaNote=카슈미르, 카르길 시, limitaPartial=철수권고(일부), wrtDt=2011-02-21}
     * {continent=중동/아프리카, countryEnName=Djibouti, countryName=지부티, id=191, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_191&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_191&file_sn=3, isoCode=DJI, limitaNote=소말리아 및 에리트레아 접경 10km 이내 지역, limitaPartial=철수권고(일부), wrtDt=2011-02-18}
     * {continent=아시아/태평양, countryEnName=Pakistan, countryName=파키스탄, id=239, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_239&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_239&file_sn=3, isoCode=PAK, limitaNote=특별여행주의보 지정 지역을 제외한 전지역, limitaPartial=철수권고(일부), wrtDt=2011-02-17}
     * {continent=미주, countryEnName=Peru, countryName=페루, id=243, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_243&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_243&file_sn=3, isoCode=PER, limitaNote=아푸리막 주 : 안다우아이라스, 친체로스 지역/ 아야쿠초 주 : 라 마르, 우안타 지역/ 우앙카벨리카 주 : 츄르캄파, 타야카하 지역/ 쿠스코 주 : 라 콘벤시온 지역/ 후닌 주 : 사티포, 우안카요, 콘셉시온 지역 , limitaPartial=철수권고(일부), wrtDt=2011-02-17}
     * {continent=유럽, countryEnName=Armenia, countryName=아르메니아, id=334, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_334&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_334&file_sn=3, isoCode=ARM, limitaNote=아제르바이잔ㆍ아르메니아 국경지역, limitaPartial=철수권고(일부), wrtDt=2011-02-16}
     * {continent=중동/아프리카, countryEnName=Iran, countryName=이란, id=176, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_176&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_176&file_sn=3, isoCode=IRN, limitaNote=시스탄발루체스탄 주, 터키ㆍ이라크 국경지역, 페르시아만 연안 3개 주(후제스탄, 부셰르, 호르모즈건(Hormozgan), limitaPartial=철수권고(일부), wrtDt=2011-02-08}
     * {continent=중동/아프리카, countryEnName=Israel, countryName=이스라엘, id=177, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_177&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_177&file_sn=3, isoCode=ISR, limitaNote=가자지구 및 가자지구 인근 5km 이내 지역, 서안지역(West Bank), limitaPartial=철수권고(일부), wrtDt=2011-02-08}
     * {continent=미주, countryEnName=Haiti, countryName=아이티, id=324, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_324&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_324&file_sn=3, isoCode=HTI, limita=철수권고, limitaNote=전지역 전지역, wrtDt=2011-02-08}
     * {continent=중동/아프리카, countryEnName=Ethiopia, countryName=에티오피아, id=156, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_156&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_156&file_sn=3, isoCode=ETH, limitaNote=아파르, 소말리, 감벨라, 베니샹굴-구무즈, 수단‧남수단‧에리트레아‧케냐 접경 10km 이내 지역, limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=중동/아프리카, countryEnName=Egypt, countryName=이집트, id=178, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_178&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_178&file_sn=3, isoCode=EGY, limitaNote=Sharm El-Sheikh를 제외한 시나이 반도 전역 및 이집트-리비아 국경지역 전역(국경도시 Salloum을 포함, 국경지역으로부터 100km까지), limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=중동/아프리카, countryEnName=Benin, countryName=베냉, id=289, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_289&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_289&file_sn=3, isoCode=BEN, limitaNote=부르키나파소 접경지역(Pendjari 국립공원 및 W 국립공원), limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=중동/아프리카, countryEnName=Morocco, countryName=모로코, id=60, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_60&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_60&file_sn=3, isoCode=MAR, limitaNote=서부 사하라 내 모래방어벽 동쪽, limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=중동/아프리카, countryEnName=Mauritania, countryName=모리타니아, id=62, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_62&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_62&file_sn=3, isoCode=MRT, limitaNote=특별여행주의보 지정지역을 제외한 전지역, limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=중동/아프리카, countryEnName=Burundi, countryName=부룬디, id=93, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_93&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_93&file_sn=3, isoCode=BDI, limitaNote=부줌부라市 제외 전 지역, limitaPartial=철수권고(일부), wrtDt=2011-01-31}
     * {continent=유럽, countryEnName=Ukraine, countryName=우크라이나, id=169, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_169&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_169&file_sn=3, isoCode=UKR, limitaNote=크림 및 돈바스지역(도네츠크, 루간스크), limitaPartial=철수권고(일부), wrtDt=2011-01-28}
     * {continent=중동/아프리카, countryEnName=Lebanon, countryName=레바논, id=40, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_40&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_40&file_sn=3, isoCode=LBN, limitaNote=리타니강 이남, 트리폴리시, 12개 팔레스타인 난민촌, 베이루트 시, 베이루트 남부교외지역(Ghobeiry, Chiayah, Haret Hraik, Borj al Brajne, Laylake), 시돈, 트리폴리 이북, 리타니강 이남, 북부 베카 지역 : 브리텔 이북, limitaPartial=철수권고(일부), wrtDt=2011-01-28}
     * {continent=아시아/태평양, countryEnName=Malaysia, countryName=말레이시아, id=56, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_56&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_56&file_sn=3, isoCode=MYS, limitaNote=사바주 동부도서 지역 및 동부해안, limitaPartial=철수권고(일부), wrtDt=2011-01-28}
     * {continent=중동/아프리카, countryEnName=Mali, countryName=말리, id=57, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_57&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_57&file_sn=3, isoCode=MLI, limita=철수권고, limitaNote=전지역 전지역, wrtDt=2011-01-27}
     * {continent=미주, countryEnName=Bolivia, countryName=볼리비아, id=92, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_92&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_92&file_sn=3, isoCode=BOL, limitaNote=태양의 섬, limitaPartial=철수권고(일부), wrtDt=2011-01-27}
     * {continent=유럽, countryEnName=Turkey, countryName=터키, id=228, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_228&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_228&file_sn=3, isoCode=TUR, limitaNote=가지안테프, 디야르바커, 마르딘, 반, 바트만, 비트리스, 빙골, 산리우르파, 시르낙, 시르트, 엘라지, 킬리스, 툰셀리, 하카리, 시리아의 국경 10km 이내 지역(히타이), limitaPartial=철수권고(일부), wrtDt=2011-01-26}
     * {continent=중동/아프리카, countryEnName=Tunisia, countryName=튀니지, id=233, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_233&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_233&file_sn=3, isoCode=TUN, limitaNote=알제리 접경지역(까세린 주 샴비산 일대, 젠두바 주), 리비아 접경지역(크사르 길랜 이남 사막지역 전역), limitaPartial=철수권고(일부), wrtDt=2011-01-18}
     * {continent=중동/아프리카, countryEnName=Niger, countryName=니제르, id=27, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_27&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_27&file_sn=3, isoCode=NER, limitaNote=특별여행주의보 지정 지역을 제외한 전지역, limitaPartial=철수권고(일부), wrtDt=2010-10-04}
     * {continent=중동/아프리카, countryEnName=Kenya, countryName=케냐, id=206, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_206&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_206&file_sn=3, isoCode=KEN, limitaNote=동부 해안가로부터 100km 이내 모든 지역, 나이로비 중부 이스트레이, 가리사, limitaPartial=철수권고(일부), wrtDt=2010-09-07}
     * {continent=중동/아프리카, countryEnName=Saudi Arabia, countryName=사우디아라비아, id=107, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_107&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_107&file_sn=3, isoCode=SAU, limitaNote=사우디-예멘 국경 인근 180km 지역(슈케이크(Shuqaiq), 아브하(Abha), 카미스 무샤이트(Khamis Mushait)市 포함), limitaPartial=철수권고(일부), wrtDt=2010-08-10}
     * {continent=중동/아프리카, countryEnName=Cameroon, countryName=카메룬, id=199, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_199&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_199&file_sn=3, isoCode=CMR, limitaNote=노르드 주(NORD), 아다모와 주(ADAMAOUA)지역, 북서부 주, 남서부 주, 최북부 주(엑스트림므-노르드(EXTREME-NORD)지역), limitaPartial=철수권고(일부), wrtDt=2010-03-26}
     * {continent=중동/아프리카, countryEnName=Central African Republic, countryName=중앙아프리카공화국, id=190, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_190&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_190&file_sn=3, isoCode=CAF, limita=철수권고, limitaNote=전지역 전지역, wrtDt=2010-03-25}
     * {continent=중동/아프리카, countryEnName=Chad, countryName=차드, id=295, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_295&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_295&file_sn=3, isoCode=TCD, limita=철수권고, limitaNote=전지역 전지역, wrtDt=2010-03-23}
     * {continent=미주, countryEnName=Venezuela, countryName=베네수엘라, id=85, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_85&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_85&file_sn=3, isoCode=VEN, limita=철수권고, limitaNote=전지역 전 지역, wrtDt=2010-03-05}
     * {continent=중동/아프리카, countryEnName=Democratic Republic Congo, countryName=콩고민주공화국, id=215, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_215&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_215&file_sn=3, isoCode=COD, limitaNote=남수단ㆍ중앙아프리카공화국과의 국경 50km 이내 지역/ 바우엘레주, 오트우엘레주, 이투리주, 북키부주, 남키부주, 마니에마주, 카사이주, 카사이오리앙탈주, 카사이상트랄주/ 舊 카탕가주 북부 지역(일부: 오트로마미주,루알라바주, 오트카탕가주), limitaPartial=철수권고(일부), wrtDt=2010-02-03}
     * {continent=중동/아프리카, countryEnName=Mozambique, countryName=모잠비크, id=63, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_63&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_63&file_sn=3, isoCode=MOZ, limitaNote=카보 델가도 주, limitaPartial=철수권고(일부), wrtDt=2010-02-03}
     * {continent=아시아/태평양, countryEnName=Papua New Guinea, countryName=파푸아뉴기니, id=240, imgUrl=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_240&file_sn=1, imgUrl2=http://www.0404.go.kr/imgsrc.mofa?atch_file_id=COUNTRY_240&file_sn=3, isoCode=PNG, limitaNote=서던 하일랜즈 주, 헬라 주, limitaPartial=철수권고(일부), wrtDt=2010-02-02}
     */
    @Ignore
    @Test
    public void fetchOne() {
        WarningFetchValue warningFetchValue = sut.fetchOne("1")
                                                 .orElse(null);
        System.out.println(warningFetchValue);
    }
}